name: Build

on: push

jobs:
  date-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test dates in CHANGELOG.md
      run:
        cat CHANGELOG.md | egrep '^#+ +[0-9-]+' | sed -r 's/([0-9]+)-([0-9]+)-([0-9]+)/\3-\2-\1/g' | sort --check -nr;

  build:
    environment: build-env
    runs-on: ubuntu-latest
    needs: date-check

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.3.3'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Build
      run:
        bundle exec middleman build --build-dir=site

    - name: Deploy
      if: github.ref == 'refs/heads/master'
      env:
        SERVER_IP_ADDRESS: dev.moysklad.ru
        APP_PREFIX: api-remap-1.3
        DEPLOY_KEY: '${{ secrets.DEPLOY_KEY }}'
      run: |
        echo $DEPLOY_KEY > ./deploy_key && chmod 600 ./deploy_key
        eval "$(ssh-agent -s)"
        echo -e "Host ${SERVER_IP_ADDRESS}\n\tStrictHostKeyChecking no\nPort 22\n" >> ~/.ssh/config
        ssh-add ./deploy_key
        ssh -i ./deploy_key app@${SERVER_IP_ADDRESS} pwd
        rm deploy_key
        rsync -r --delete-after --quiet site/ app@${SERVER_IP_ADDRESS}:./${APP_PREFIX}
