# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Build

on: push

jobs:
  date-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test dates in CHANGELOG.md
      run:
        cat CHANGELOG.md | egrep '^#+ +[0-9-]+' | sed -r 's/([0-9]+)-([0-9]+)-([0-9]+)/\3-\2-\1/g' | sort --check -nr;

    - name: Test dates in source/includes/changelog/_changelog.md"
      run:
        cat source/includes/changelog/_changelog.md | egrep '^#+ +[0-9-]+' | sed -r 's/([0-9]+)-([0-9]+)-([0-9]+)/\3-\2-\1/g' | sort --check -nr;

  build:
    runs-on: ubuntu-latest
    needs: date-check

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.3.3'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build
      run:
        bundle exec middleman build --build-dir=site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy
      if: github.ref == 'refs/heads/master'
      run: |
        openssl aes-256-cbc -K $encrypted_fd0bb6467860_key -iv $encrypted_fd0bb6467860_iv
        in deploy_key.enc -out deploy_key -d
        eval "$(ssh-agent -s)"
        chmod 600 ./deploy_key
        echo -e "Host ${SERVER_IP_ADDRESS}\n\tStrictHostKeyChecking no\nPort 22\n" >> ~/.ssh/config
        ssh-add ./deploy_key
        ssh -i ./deploy_key app@${SERVER_IP_ADDRESS} pwd
        rm deploy_key.enc deploy_key
